apiVersion: apps/v1

kind: Deployment
metadata:
  name: front-end-deployment
  labels:
    app: front-end

spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end 
          image: "uploader-frondend:0.0.3"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: back-end-config