apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend-service
spec:
  selector:
    app: {{ .Values.appName }}-frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

