apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend-service
spec:
  selector:
    app: {{ .Values.appName }}-backend
  type: ClusterIP
  ports:
    - targetPort: 5001
      port: 5001